In [25]:
import numpy as np
import pandas as pd

In [26]:
df1 = pd.read_csv('FinalData.csv')
df1=df1[0:11]
df1

,YEAR,Gross_Weight_Of\n_Goods_Handled\n(in thousand tonnes),Volume(inTEUs)_of_\ncontainers_handled,Pasangers_embarked_and_disembarkes\n(in_thousands),Pasangers_inward\n(in thousands),Pasangers_outward\n(in thousands),ShortSeaShipping_Weight\n_of_Goods_transported\n(in thousands tonnes),DeepSeaShipping_Weight_\nof_Goods_transported\n(in thousand tonnes),Marinetime_goods_transport_performed\n(inExclusiveEconomicZoneofthecountry\n(inMillionTonne-kilometer)),Total_Vessels,GeneralCargo(NonSpecialised)\nvessel,Pasanger_Ship\nVessel,Liquid_Bulk_Tanker\nVessel,Container_Ship\nVessel,Other_Vessels\nJ-K-L,Gross_tonnage_in_thousands_by_all types_of_\nvessels\n,Gross_Value_Added \n(in Thousand Euros)\nin Marinetime_transport_sector,Turnover(in thousand euros)\nin Marinetime_transport_sector
0,2010.0,3034880.0,53317.0,396348.0,198934.0,197414.0,1618837.0,946958.0,4448441.0,2134012.0,1191665.0,650397.0,94503.0,91115.0,106332.0,13739816.0,30004.0,134200.0
1,2011.0,3094060.0,63981.0,384800.0,192466.0,192334.0,1636150.0,1023042.0,4525844.0,2181926.0,1604546.0,301284.0,92285.0,78854.0,104957.0,14077937.0,27108.0,136167.0
2,2012.0,3154395.0,76778.0,371689.0,186219.0,185470.0,1614816.0,1034662.0,4604594.0,2096398.0,1536204.0,296129.0,90547.0,70608.0,102910.0,13905003.0,27419.0,145742.0
3,2013.0,3215906.0,78314.0,372732.0,186250.0,186028.0,1610880.0,1032035.0,4684714.0,2016989.0,1480749.0,275622.0,88853.0,69448.0,102317.0,13711175.0,29049.0,141348.0
4,2014.0,3287210.0,82884.0,365240.0,182617.0,182086.0,1638403.0,1053376.0,4746385.0,2068414.0,1522402.0,292222.0,85499.0,66440.0,101851.0,13679852.0,28785.0,139612.0
5,2015.0,3343755.0,82206.0,368222.0,184268.0,183111.0,1660535.0,1063441.0,4850032.0,1991274.0,1430425.0,314502.0,82067.0,72050.0,92230.0,14280662.0,32476.0,150563.0
6,2016.0,3376704.0,86539.0,370467.0,185274.0,184105.0,1702834.0,1040279.0,4842221.0,1989123.0,1403199.0,328386.0,81883.0,75510.0,100145.0,14911085.0,27088.0,139315.0
7,2017.0,3476076.0,89692.0,389537.0,194779.0,193390.0,1711477.0,1096029.0,5059154.0,2026259.0,1440847.0,319711.0,83334.0,75640.0,106727.0,15447891.0,31032.0,155320.0
8,2018.0,3584537.0,96798.0,411006.0,205451.0,204047.0,1771398.0,1137964.0,5207869.0,2189422.0,1583477.0,340848.0,83909.0,75639.0,105549.0,16173588.0,30123.0,160310.0
9,2019.0,3587258.0,96573.0,418488.0,208739.0,208265.0,1800469.0,1169011.0,5317875.0,2278469.0,1649665.0,363473.0,86846.0,71518.0,106967.0,16288379.0,34244.0,163249.0
10,2020.0,3325646.0,94297.0,230121.0,115115.0,114599.0,1682005.0,1067160.0,5036425.0,1944030.0,1503487.0,215768.0,81079.0,66720.0,76976.0,13250266.0,29509.0,147421.0

In [27]:
X = df1.drop('Gross_Value_Added \n(in Thousand Euros)\nin Marinetime_transport_sector', axis=1)  
#X = X.drop('Turnover(in thousand euros)\nin Marinetime_transport_sector', axis=1)

#X = X.drop('YEAR', axis=1)
#X = X.drop('Gross_Weight_Of\n_Goods_Handled\n(in thousand tonnes)', axis=1)
#X = X.drop('Volume(inTEUs)_of_\ncontainers_handled', axis=1)
#X = X.drop('Pasangers_embarked_and_disembarkes\n(in_thousands)', axis=1)
X = X.drop('Pasangers_inward\n(in thousands)', axis=1)
X = X.drop('Pasangers_outward\n(in thousands)', axis=1)
#X = X.drop('ShortSeaShipping_Weight\n_of_Goods_transported\n(in thousands tonnes)', axis=1)
#X = X.drop('DeepSeaShipping_Weight_\nof_Goods_transported\n(in thousand tonnes)', axis=1)
#X = X.drop('Marinetime_goods_transport_performed\n(inExclusiveEconomicZoneofthecountry\n(inMillionTonne-kilometer))', axis=1)
#X = X.drop('Total_Vessels', axis=1)

X = X.drop('Other_Vessels\nJ-K-L', axis=1)
X = X.drop('Container_Ship\nVessel', axis=1)
X = X.drop('Liquid_Bulk_Tanker\nVessel', axis=1)
X = X.drop('Pasanger_Ship\nVessel', axis=1)
X = X.drop('GeneralCargo(NonSpecialised)\nvessel', axis=1)


#X = X.drop('Gross_tonnage_in_thousands_by_all types_of_\nvessels\n', axis=1)
Y = df1['Gross_Value_Added \n(in Thousand Euros)\nin Marinetime_transport_sector']

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
from sklearn.metrics import mean_squared_error

In [29]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=2, random_state=42)
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.0